CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  nome VARCHAR(100) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  user_id INT UNSIGNED NOT NULL PRIMARY KEY,
  ore_1 SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  ore_2 SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  ore_3 SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  ore_4 SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  ore_5 SMALLINT UNSIGNED NOT NULL DEFAULT 480,
  ore_6 SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ore_7 SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  pausa_default SMALLINT UNSIGNED NOT NULL DEFAULT 60,
  soglia_straord SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  arrotondamento SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  paga_oraria DECIMAL(8,2) NOT NULL DEFAULT 0,
  magg_straord DECIMAL(5,2) NOT NULL DEFAULT 25,
  magg_festivo DECIMAL(5,2) NOT NULL DEFAULT 50,
  patrono CHAR(5) NOT NULL DEFAULT '',
  azienda VARCHAR(150) NOT NULL DEFAULT '',
  CONSTRAINT fk_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS presenze (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  data DATE NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'lavoro',
  entrata1 TIME NULL,
  uscita1 TIME NULL,
  entrata2 TIME NULL,
  uscita2 TIME NULL,
  pausa_min SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  permesso_min SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  note VARCHAR(500) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_user_data (user_id, data),
  CONSTRAINT fk_presenze_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
